baseURL = "https://radio-paris-samarcande.eu/"
languageCode = "fr-fr"
title = "Maurice — Photographies"

[params]
  snipcartApiKey = "NjMxNDk3YzctMjU3My00ZTFjLThmNGQtZDcwOGY1OGNhYTc4NjM5MTg1OTgwMjU3NDMwNzMy"
  description = "Photographies de voyage, de Paris à Samarcande"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menus]
  [[menus.main]]
    name = "Galerie"
    pageRef = "/"
    weight = 10
  [[menus.main]]
    name = "Archive"
    pageRef = "/photos"
    weight = 20
  [[menus.main]]
    name = "À propos"
    pageRef = "/a-propos"
    weight = 30
